version: "3.7"

services:
  backend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure    
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:80
    depends_on:
      - backend
