version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3002:80
    depends_on:
      - backend


  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: codigodebarras
      POSTGRES_USER: luuhsantanafs
      POSTGRES_PASSWORD: euamoJesus102030
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    


  
