version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    # depends_on:
    #   - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3002:80

#   postgres:
#     image: postgres:latest
#     container_name: bancodedados
#     environment:
#       POSTGRES_DB: codigodebarras
#       POSTGRES_USER: luuhsantanafs
#       POSTGRES_PASSWORD: Lucas102030
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./bancodedados:/var/lib/postgresql/data
#     networks:
#       - redebancodedados

# networks:
#   redebancodedados:
#     driver: bridge
