version: "3.7"

services:
  backend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure    
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - eicheferede

  frontend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 321:80
    depends_on:
      - backend
    networks:
      - eicheferede

  db:
    image: postgres
    restart: always
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: euamoJesus102030
    volumes:
      - ./Docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - eicheferede

networks:
  eicheferede:
    driver: bridge