version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: euamoJesus102030
    volumes:
      - ./Docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - eicheferede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    restart: always
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - eicheferede

  frontend:
    restart: always
    depends_on:
      - db
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 321:80
    networks:
      - eicheferede

networks:
  eicheferede:
    driver: bridge
