-- CreateTable
CREATE TABLE "AlumifranPrecos" (
    "id" SERIAL NOT NULL,
    "procod" TEXT NOT NULL,
    "prodes" TEXT NOT NULL,
    "promar" TEXT NOT NULL,
    "prouni" TEXT NOT NULL,
    "proatinat" TEXT NOT NULL,
    "procp1" TEXT NOT NULL,
    "procp2" TEXT NOT NULL,
    "proref" TEXT NOT NULL,
    "prosit" TEXT NOT NULL,
    "procp3" TEXT NOT NULL,
    "procp4" TEXT NOT NULL,
    "propeso" TEXT NOT NULL,
    "procodipi" TEXT NOT NULL,
    "procest" TEXT NOT NULL,
    "proqmi" TEXT NOT NULL,
    "propdc" TEXT NOT NULL,
    "propdv" TEXT NOT NULL,
    "propcv" TEXT NOT NULL,
    "proicm" TEXT NOT NULL,
    "proipi" TEXT NOT NULL,
    "comissao" TEXT NOT NULL,
    "profin" TEXT NOT NULL,
    "profre" TEXT NOT NULL,
    "proipf" TEXT NOT NULL,
    "proipe" TEXT NOT NULL,
    "procfv" TEXT NOT NULL,
    "procop" TEXT NOT NULL,
    "procus" TEXT NOT NULL,
    "prorent" TEXT NOT NULL,
    "procapt" TEXT NOT NULL,
    "prodesc" TEXT NOT NULL,
    "proipecus" TEXT NOT NULL,
    "prodifimp" TEXT NOT NULL,
    "proemb" TEXT NOT NULL,
    "prodescon" TEXT NOT NULL,
    "prolotvd" TEXT NOT NULL,
    "proorig" TEXT NOT NULL,
    "procsosn" TEXT NOT NULL,
    "procofins" TEXT NOT NULL,
    "proadc" TEXT NOT NULL,
    "clf_des" TEXT NOT NULL,
    "clf_ncm" TEXT NOT NULL,

    CONSTRAINT "AlumifranPrecos_pkey" PRIMARY KEY ("id")
);
